In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define vocab size
voc_size=10000

In [5]:
## One hot representation for every word

one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2485, 4296, 1236, 9122],
 [2485, 4296, 1236, 8215],
 [2485, 6472, 1236, 7883],
 [7987, 8782, 393, 2782, 4062],
 [7987, 8782, 393, 2782, 202],
 [2688, 2485, 5722, 1236, 2318],
 [9183, 2491, 7525, 2782]]

## Word Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

### we use pad sequences to set the maximum sentence lenght to work in RNN

In [7]:
import numpy as np

In [8]:
sent_length=8                    # pad sequences helps us to set the lengt as 8, it will set zeros [0, 0, 0, 0, 3225, 6458, 4987, 6211]
Embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
Embedding_docs

array([[   0,    0,    0,    0, 2485, 4296, 1236, 9122],
       [   0,    0,    0,    0, 2485, 4296, 1236, 8215],
       [   0,    0,    0,    0, 2485, 6472, 1236, 7883],
       [   0,    0,    0, 7987, 8782,  393, 2782, 4062],
       [   0,    0,    0, 7987, 8782,  393, 2782,  202],
       [   0,    0,    0, 2688, 2485, 5722, 1236, 2318],
       [   0,    0,    0,    0, 9183, 2491, 7525, 2782]], dtype=int32)

## Feature representation

In [9]:
dim=10

In [10]:
##model=Sequential()
#model.add(Embedding(voc_size,dim,input_length=sent_length))       # pass paramarters into embedding layer
#model.compile('adam','mse')                                       ## optimizer adam and loss fucntion mse

In [11]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim= dim))  # No need for input_length
# Compile the model
model.compile(optimizer='adam', loss='mse')


In [12]:
# Print the model summary (not yet built)
print("Before feeding input:")
print(model.summary())

# Feed dummy input data to build the model
dummy_input = np.random.randint(0, voc_size, (1, sent_length))  # Batch size = 1, Sequence length = 20
model.predict(dummy_input)  # This will build the model

# Print the model summary (after building)
print("After feeding input:")
print(model.summary())

Before feeding input:


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step
After feeding input:


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

None


In [13]:
model.predict(Embedding_docs)       # every word represented by 10 dimensions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[[ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.01861108,  0.01040823,  0.01365659,  0.03512776,
          0.04616379,  0.04907788,  0.00533162,  0.03356911,
         -0.00633596,  0.04022571],
        [ 0.04197159,  0.02347282, -0.03997086, -0.04316352,
          0.02028095, -0.01574666,  0.00971476, -0.04433022,
          0.02852005, -0.01057933],
        [-0.01102672,  0.02111081, -0.03314646,  0.0

In [14]:
Embedding_docs[0]

array([   0,    0,    0,    0, 2485, 4296, 1236, 9122], dtype=int32)

In [15]:
# Example: Assume Embedding_docs[0] is a sequence of integers
# representing tokenized input data
sequence = Embedding_docs[0]  # Single sequence

# Add a batch dimension
sequence_with_batch = np.expand_dims(sequence, axis=0)  # Shape: (1, sequence_length)

# Predict using the model
output = model.predict(sequence_with_batch)
output

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


array([[[ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.03966038, -0.02511128, -0.04023644, -0.02464857,
         -0.03786128,  0.01159413, -0.03030049, -0.00277288,
          0.01048294,  0.00167454],
        [ 0.01861108,  0.01040823,  0.01365659,  0.03512776,
          0.04616379,  0.04907788,  0.00533162,  0.03356911,
         -0.00633596,  0.04022571],
        [ 0.04197159,  0.02347282, -0.03997086, -0.04316352,
          0.02028095, -0.01574666,  0.00971476, -0.04433022,
          0.02852005, -0.01057933],
        [-0.01102672,  0.02111081, -0.03314646,  0.0

### now the entire array([   0,    0,    0,    0, 6516, 2298,  938, 4810], dtype=int32) converted to above array

In [16]:
print("Output shape:", output.shape)

Output shape: (1, 8, 10)
